run sudo with password
RackHD/on-build-config pull request #222
Opened 2017-06-13 08:11 UTC by panpan0000

to ensure security, the jenkins account on vmslaves is required password.

so directlly using sudo in scripts which run on vmslaves,  will fail "sudo: no tty present and no askpass program specified"

@PengTian0

2017-06-13 08:56 UTC, anhou approved these changes

2017-06-13 08:57 UTC, PengTian0 commented
:+1:

2017-06-13 08:58 UTC, iceiilin approved these changes

2017-06-13 15:44 UTC, stuart-stanley requested changes
-1 why is a _test_ script installing global software to begin with? The reason build-VM's use non-privileged users is to prevent things like this.

2017-06-14 01:47 UTC, panpan0000 commented
after discussion with @PengTian0 , we think using virtualEnv is reasonable per @stuart-stanley's comment.
but taken test.sh.in will never be able to run outside Jenkins for now. so I don't think this comment is gating.
otherwise, the whole test.sh.in will be a "-1" for now.
but another problem of this PR is , vnc_record.sh is run inside vagrant, so the SUDO_PWD is not applicable . this change should be in @PengTian0 's docker PR (next step)

2017-06-14 03:30 UTC, panpan0000 commented
close this PR.
@PengTian0  will do the pip install vnc2flv inside a virtualENV in her PR: https://github.com/RackHD/on-build-config/pull/219

2017-06-14 03:30 UTC, closed without merging