RAC:4189: Release notes automation
RackHD/on-build-config pull request #229
Opened 2017-06-22 10:20 UTC by kellylu2sym

This is the script to help to generate release notes in Confluence automatically.

2017-06-22 17:33 UTC, panpan0000 requested changes
can we describe more details in PR desc

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +    new_row = new_row.replace(configs["qurey_version"],version)
move to config file and use the real page

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +    config_file = "releaseNoteConfig.conf"
better naming as xxxx.conf which xxxx is this python script file name?

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteConfig.conf
> +temp_start_date = 1999-01-01
comments in config file to explain what every item means

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +    post_response = requests.post(configs["rest_url_base"], headers = header, auth = (user_name , passwd), data = json.dumps(content))
no error check on post response

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +                          help = "This arguments present the version of release note",
this argument(no s)

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +    parent_id = data["results"][0]["id"]
is parent_id the id of template page itself? it should be another page whose page name defined in config

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +    new_row = new_row.replace(configs["qurey_version"],version)
i meant the release_page_name

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +    print post_response
real check than print?

2017-06-22 17:33 UTC, panpan0000 commented on build-release-tools/application/releaseNoteConfig.conf
> +template_new_row = <tr><td colspan="1"><span>&nbsp;Sprint Release</span></td><td colspan="1">RELEASE_VERSION</td><td colspan="1">2017/06/11</td><td colspan="1"><ac:link><ri:page ri:content-title="Rac
i just remind myself about the official release page there may be two tables instead of one 😭

2017-06-23 03:31 UTC, panpan0000 commented
write more description for @kellylu2sym 

(1) script will be triggered after Sprint Release build successfully
(2) it will create a release page(named release notes x.y.z ) under https://rackhd.atlassian.net/wiki/display/RAC1/Release+Notes+Lists
in this page, some JIRA query will show feature/issue fixed in this sprint.

![image](https://user-images.githubusercontent.com/14049268/27465656-7baecd60-5807-11e7-8d66-f18651347073.png)

(3) then it will add a new row about x.y.z information into https://rackhd.atlassian.net/wiki/display/RAC1/RackHD+Release+Page
![image](https://user-images.githubusercontent.com/14049268/27465635-533e4b08-5807-11e7-9dfa-6b2590865e2a.png)

2017-06-26 02:59 UTC, panpan0000 approved these changes

2017-06-27 03:15 UTC, changev commented on build-release-tools/application/releaseNoteAuto.py
> +            #print name, value
You can delete this line

2017-06-27 03:18 UTC, changev commented on build-release-tools/application/releaseNoteAuto.py
> +    response = requests.get(template_url,  auth=(user, pwd))
Add response validation here will make it more robust.

2017-06-27 03:19 UTC, changev approved these changes

2017-06-28 01:11 UTC, panpan0000 commented on build-release-tools/application/releaseNoteAuto.py
> +    response = requests.get(template_url,  auth=(user, pwd))
can you please address @changev's  comment

2017-06-28 04:32 UTC, panpan0000 commented
@kellylu2sym , you have 10+ commits in your PR.
does every commit make sense ? if not, can you please ```rebase -i```  to squash them ?

2017-06-28 04:51 UTC, panpan0000 commented
besides, I recommended to write the final JQL example as comment in the code.
(1) help people to understand what your JQL will be 
(2) in case the ReleaseTemplate being deleted by accident, you will still have  the JQL

2017-06-30 04:12 UTC, panpan0000 approved these changes
+1

2017-06-30 04:21 UTC, iceiilin approved these changes

2017-06-30 04:22 UTC, merged