RAC-4485 Remove Generated Files
RackHD/on-build-config pull request #273
Opened 2017-07-17 18:08 UTC by BrentHiggins

* Updated version of the PR to remove generated files

2017-07-17 18:12 UTC, BrentHiggins commented
@jimturnquist @hohene

2017-07-17 18:40 UTC, johren requested changes

2017-07-17 18:40 UTC, johren commented on .gitignore
> +post-deploy.sh
Missing pre-deploy.sh

2017-07-17 18:41 UTC, johren commented on .gitignore
> +post-deploy.sh
And vnc-record.sh

2017-07-17 20:37 UTC, johren commented on .gitignore
> +.nvmrc
.nvmrc no longer needed since .nvmrc.in was removed in a previous PR.

2017-07-17 21:29 UTC, jimturnquist approved these changes

2017-07-17 22:14 UTC, johren commented on .gitignore
> +vnc-record.sh
Actually, it is an underscore rather than a dash.  I got it wrong in the comment.  
vnc_record.sh

2017-07-18 00:48 UTC, panpan0000 commented
Thank you to doing that !
@PengTian0  for awareness.

2017-07-18 04:58 UTC, PengTian0 commented
:+1:

2017-07-18 18:39 UTC, johren approved these changes

2017-07-18 18:41 UTC, merged